### ISSUE TITLE
Clarify when version information is needed

### ISSUE THREAD

**Issue by gtback** [STIXProject/stix-validator#56]
Now that we are actively using stix-validator to check the in-development versions of the schemas, we need to clarify when version information is required in instance documents we are checking, as well as how using the `schema_dir` argument impacts the version determination process.

http://stix-validator.readthedocs.org/en/latest/examples/schema.html?highlight=version#stix-and-cybox-versions

**Comment by bworrell** [comment]
@gtback, blargh! This made me dive back into the documentation and code and made me realize that I unintentionally changed the validation behavior pretty drastically with this v2.1.0 branch. 

Previously, the validation code didn't perform any sort of version checking/verifying if the user passed in a schema directory or specified validation via `@xsi:schemaLocation`. 

Now users are required to provide a version number, either via a parameter or the version attribute(s) in the input document. I think I should change it back to he way it was previously. What do you think?

**Comment by bworrell** [comment]
Also, I agree that it needs to be made clearer in the documentation :)

**Comment by gtback** [comment]
I agree it should be changed back, or at least give users the option to "test against this set of schemas (in the schema_dir), regardless of what version information you find."

**Comment by bworrell** [comment]
Cool! I updated the code here https://github.com/STIXProject/stix-validator/compare/versions and have been updating the docs locally but am fighting with cygwin and sphinx at the moment. Once I review my documentation changes I'll issue a pull request.
