### ISSUE TITLE
Check for timezone in all timestamps

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stix-validator#6]
All timestamp fields should have a timezone specified. It's a warning if they don't.

**Comment by bworrell** [comment]
d71b2a2e4ffa988bf9b2b6082b0dcfe1b3517c58. checks that `@timestamp` values on the major STIX component types have timezone information. We probably need to check that reference types are using timezones as well.

**Comment by bworrell** [comment]
Actually, I think it does work for all relationship types. I am going to close this out :)
