### ISSUE TITLE
Validation fails for indicator hashes

### ISSUE THREAD

**Issue by jhemp** [STIXProject/stix-validator#69]
I get these warnings
    [!] Indicator Pattern Properties Missing Condition Attributes
        [-] line : 261
        [-] message : None
        [-] id : None
        [-] idref : None
        [-] tag : {http://cybox.mitre.org/common-2}Type
        [-] parent indicator id : ce1sus:Indicator-14eafccd-60b9-4976-a454-2a0986902394
        [-] parent indicator line : 246
        --------------------------------------------------------------------------------

for the fillowing lines in the xml
        <stix:Indicator id="ce1sus:Indicator-14eafccd-60b9-4976-a454-2a0986902394" timestamp="2015-06-12T15:36:00.939038+00:00" xsi:type='indicator:IndicatorType'>
            <indicator:Title>Indicators for "File Hash Watchlist"</indicator:Title>
            <indicator:Type xsi:type="stixVocabs:IndicatorTypeVocab-1.1">File Hash Watchlist</indicator:Type>
            <indicator:Description>Auto-generated indicators</indicator:Description>
            <indicator:Valid_Time_Position>
                <indicator:Start_Time precision="second">2015-06-12T15:36:00.894255</indicator:Start_Time>
                <indicator:End_Time precision="second">2015-06-12T15:36:00.894255</indicator:End_Time>
            </indicator:Valid_Time_Position>
            <indicator:Observable id="ce1sus:Observable-8a888217-0d9c-40b5-b458-2d0d4db79d2f">
                <cybox:Observable_Composition operator="OR">
                    <cybox:Observable id="ce1sus:Observable-f5079b7d-afdc-441d-86a3-94d23caefea4">
                        <cybox:Object id="ce1sus:Object-b39863e9-997b-4ecf-ac58-a4f9e4eca0a1">
                            <cybox:Properties xsi:type="FileObj:FileObjectType">
                                <FileObj:Hashes>
                                    <cyboxCommon:Hash>
                                        <cyboxCommon:Type xsi:type="cyboxVocabs:HashNameVocab-1.0">MD5</cyboxCommon:Type>
                                        <cyboxCommon:Simple_Hash_Value>083f9d1d2d2db5e7eaaf5dc3f563357f</cyboxCommon:Simple_Hash_Value>
                                    </cyboxCommon:Hash>
                                </FileObj:Hashes>
                            </cybox:Properties>
                        </cybox:Object>
                    </cybox:Observable>

However it does not make sense to have a condition on hashes? moreover without indicator as plain observable it is valid?

**Comment by gtback** [comment]
`condition` can (and should, in this case) be set to `Equals`. See https://stixproject.github.io/documentation/suggested-practices/#creating-pattern-observables-for-indicators

**Comment by jhemp** [comment]
Ok makes also sense thanks sorry for the commotion.

On 12 June 2015 19:37:29 CEST, Greg Back <notifications@github.com> wrote:
>`condition` can (and should, in this case) be set to `Equals`. See
>https://stixproject.github.io/documentation/suggested-practices/#creating-pattern-observables-for-indicators
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/STIXProject/stix-validator/issues/69#issuecomment-111569879

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gtback** [comment]
No worries, @jhemp! We're here to help. And sorry for the short (and perhaps brusque-sounding) response. I was in a hurry on Friday.
