### ISSUE TITLE
Break out profile conversion options in stix_validator.py

### ISSUE THREAD

**Issue by bworrell** [STIXProject/stix-validator#71]
I keep wanting a simple "convert this Excel profile into schematron/XSL" script. Though it's easy to use the `--schematron-out` and `--xslt-out` options in `stix_validator.py`, I want to take them out and put them in a dedicated translation script (or scripts),

Maybe `profile-to-sch.py` and `profile-to-xslt.py` or just `transform-profile.py` with an `--fmt=xslt,sch` option.

**Comment by gtback** [comment]
+1. All of the above. `profile-to-sch.py` and `profile-to-xslt.py` should write to stdout. `transform-profile.py` should use the base name of the profile and make a .xsl and .sch (or whatever the standard extensions are) in the same directory as the profile. Both should be thin wrappers around functionality already contained in the sdv package.

**Comment by Bojak4616** [comment]
Will be working on my own branch to create the two separate scripts.

**Comment by bworrell** [comment]
@gtback, I like the ideas, thanks! 

@Bojak4616, let's just do `profile-to-sch.py` and `profile-to-xslt.py` for now and think about `transform-profile.py` as a possibility for later.

Like @gtback mentioned, these should really just call out to [`sdv.profile_to_schematron()`](http://stix-validator.readthedocs.org/en/stable/api/sdv.html#sdv.profile_to_schematron) and [`sdv.profile_to_xslt()`](http://stix-validator.readthedocs.org/en/stable/api/sdv.html#sdv.profile_to_xslt) and can probably just call `print lxml.etree.tostring(result, pretty_print=True, xml_declaration=True)` on the transformation `result`.

**Comment by Bojak4616** [comment]
Closed in #72
