### ISSUE TITLE
Order of elements gives error

### ISSUE THREAD

**Issue by RonanC** [STIXProject/stix-validator#77]
The `stix-validator` shows an error when elements are not in the correct order.

The example below shows the `Import` and `Function` elements within the `Extracted_Features` element.

This xml snippet fails the validation, but if I switch the function and import code then it will pass.

```xml
<FileObj:Extracted_Features>

    <cyboxCommon:Functions xsi:type="cyboxCommon:FunctionsType">
        <cyboxCommon:Function condition="Equals" apply_condition="ANY" xsi:type="cyboxCommon:StringObjectPropertyType">Function</cyboxCommon:Function>
    </cyboxCommon:Functions>

    <cyboxCommon:Imports xsi:type="cyboxCommon:ImportsType">
        <cyboxCommon:Import condition="Equals" apply_condition="ANY" xsi:type="cyboxCommon:StringObjectPropertyType">Import</cyboxCommon:Import>
    </cyboxCommon:Imports>

</FileObj:Extracted_Features>
```

The cybox schema states the objects in the following order:
- Strings
- Imports
- Functions
- Code_Snippets

Schema for reference: https://cybox.mitre.org/language/version2.0/xsddocs/extensions/platform/cpe2.3/1.0/cybox_common_xsd.html#ExtractedFeaturesType

**Error Message:**
```sh
[!] XML Schema: False
    [!] File%20Function%20and%20Import.xml:33:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://cybox.mitre.org/common-2}Imports': This element is not expected. Expected is ( {http://cybox.mitre.org/common-2}Code_Snippets ).
```

I don't think the order of the elements should matter and that this issue is caused by some rule in the validator.

Can someone confirm this?

**Comment by ikiril01** [comment]
Hello @RonanC, I believe the behavior of the validator in this instance is correct. The reason is that the elements of the ExtractedFeaturesType are defined in an `xs:sequence` block, which means that they MUST be present in instance data in the order defined by the sequence.

**Comment by gtback** [comment]
Thanks for the question/suggestion, @RonanC. 

In this case, @ikiril01 is correct that the validator just enforces what is required by the STIX and CybOX schemas. In this case, the `xs:sequence` requires `Imports` to come before `Functions`, so there's nothing we can do in the validator, that wouldn't involve the validator saying that non-schema-compliant content is "valid" (which we clearly don't want). The change would have to be made in the schemas themselves; however the STIX 1.x and CybOX 2.x schemas are no longer being developed, and we don't anticipate any future versions. 

Additionally, the use of `xs:sequence` makes parsing the XML content more predictable for consumers. Is there a particular reason having `Functions` before `Imports` is necessary?
