### ISSUE TITLE
Consider refactoring scripts for better integration in other APIs

### ISSUE THREAD

**Issue by gtback** [STIXProject/stix-validator#79]
The scripts under `sdv/scripts` cannot be directly imported because of the hyphens in the file names. We should move that functionality to a `sdv.cli` module (or package), and use `entry_points` in setup.py to call the functions in the `cli` module. This is how a lot of tools like `pip` work.

cc @emmanvg .

**Comment by emmanvg** [comment]
The simplest solution I can think of is to simply rename the modules to use an underscore instead of a hyphen. Followed by adding the `entry_points` to setup.py and that way we can retain the same behavior when invoked from a CLI and will allow the scripts to be imported. Example:

``` python
setup(
    name='stix-validator',
    description='APIs and scripts for validating STIX and CybOX documents.',
    author='The MITRE Corporation',
    author_email='stix@mitre.org',
    url='http://stix.mitre.org/',
    version=get_version(),
    packages=find_packages(),
    entry_points={
        'console_scripts': [
            'stix-validator = sdv.scripts.stix_validator:main',
            'cybox-validator = sdv.scripts.cybox_validator:main',
            'profile-to-sch = sdv.scripts.profile_to_sch:main',
            'profile-to-xslt = sdv.scripts.profile_to_xslt:main',
        ],
    },
    include_package_data=True,
    install_requires=install_requires,
    extras_require=extras_require,
    long_description=readme,
    keywords="stix cybox xml validation validator stix-validator"
)
```

What do you think @gtback ?

**Comment by gtback** [comment]
Sounds good, @emmanvg . Do you want to take a crack a this? Not urgent, but is potentially pretty quick.
